### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gluefox** [MinghanLi/UniVS#1]
Hey, what is the license of the repo?

**Comment by MinghanLi** [comment]
Our code is built on [Detectron2](https://github.com/facebookresearch/detectron2), [Mask2Former](https://github.com/facebookresearch/Mask2Former), [VITA](https://github.com/sukjunhwang/VITA), [ReferFormer](https://github.com/wjn922/ReferFormer), [SAM](https://github.com/facebookresearch/segment-anything), [UniNEXT](https://github.com/MasterBin-IIAU/UNINEXT) and so on. Thereforem our code inherits the license of the above methods. If it is for non-academic use, please check the license carefully.
