### ISSUE TITLE
err when testing on a custom video

### ISSUE THREAD

**Issue by cityWonder** [MinghanLi/UniVS#10]
Following your instructions, I have installed the environment. There are import errors when I infer the videos. The logs are as follows:
sh tools/test_custom_videos/test_custom_videos.sh
Number of videos: 4
Processing video 1/4
Unsupported video format: json
total_frames: 83
Saving data into datasets/custom_videos/raw/test.json
Traceback (most recent call last):
  File "/home/chengmofan/UniVS/mask2former/modeling/pixel_decoder/ops/functions/ms_deform_attn_func.py", line 22, in <module>
    import MultiScaleDeformableAttention as MSDA
ImportError: /home/chengmofan/.conda/envs/tscd/lib/python3.10/site-packages/MultiScaleDeformableAttention-1.0-py3.10-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1017SymbolicShapeMeta18init_is_contiguousEv

**Comment by MinghanLi** [comment]
You miss one step in the [requirements](https://github.com/MinghanLi/UniVS/blob/main/INSTALL.md)

After preparing the required environment, run the following command to compile CUDA kernel for MSDeformAttn: CUDA_HOME must be defined and points to the directory of the installed CUDA toolkit.

cd mask2former/modeling/pixel_decoder/ops
sh make.sh

**Comment by cityWonder** [comment]
Actually I have already done that step. Now I re-downloaded the source code, re-installed it, and the problem disappeared. Thank you for your prompt reply and open-sourcing such a great work.

**Comment by MinghanLi** [comment]
Cheers！If have any question about the code, please feel free to contact us.
