### ISSUE TITLE
Gth

### ISSUE THREAD

**Issue by geek-APTX4869** [MinghanLi/UniVS#12]
Dear author：
  G<sup>th</sup>是什么含义呢？

**Comment by MinghanLi** [comment]
Can you provide more information about this question? Is it in our paper or code? Thanks

**Comment by geek-APTX4869** [comment]
The second and fourth columns of Table 1 (b) in the paper

**Comment by MinghanLi** [comment]
To evaluate the performance, region jaccard $J$ and countour accuracy $F$ are computed for ‘seen’ and ‘unseen’ classes
separately, denoted by subscripts $s$ and $u$. G^th is the average (J&F) over both seen and unseen classes.

Please refer to Appendix A.2. of our paper for more details.
