### ISSUE TITLE
 No such file or directory: 'datasets/concept_emb/combined_datasets_cls_emb_rn50x4.pth'

### ISSUE THREAD

**Issue by ljh-7** [MinghanLi/UniVS#13]
Why is this problem occurring?  No such file or directory: 'datasets/concept_emb/combined_datasets_cls_emb_rn50x4.pth'

**Comment by MinghanLi** [comment]
You can download it from [here](https://github.com/MinghanLi/UniVS/blob/7415d31d149a7a3c2f5a7616a854af1a3e2dfb61/datasets/README.md?plain=1#L5).

**Comment by ljh-7** [comment]
> You can download it from [here](https://github.com/MinghanLi/UniVS/blob/7415d31d149a7a3c2f5a7616a854af1a3e2dfb61/datasets/README.md?plain=1#L5).

Thanks a lot! If I want to fine-tune your model with a custom dataset and have already registered the custom dataset in detectron2, what is the training data format for UniVS? The format of my dataset is shown in the figure below.
![微信图片_20241219153408](https://github.com/user-attachments/assets/d9769810-48ef-4298-8110-bb6f3d8d210d)

**Comment by MinghanLi** [comment]
To fine-tune UniVS on the custom dataset, you need to convert it into a supported structure. For more details, please refer to the dataset [README.md](https://github.com/MinghanLi/UniVS/tree/main/datasets). Here are the basic instructions:

1. Convert your data into the standard [VIS (YTVIS2021)](https://competitions.codalab.org/competitions/28988), [VSS (VSPW)](https://github.com/VSPW-dataset/VSPW-dataset-download), or [VPS (VIPSeg)](https://github.com/VIPSeg-Dataset/VIPSeg-Dataset/tree/main) annotation formats
2. Convert the data into the supported structure by using the [VIS](https://github.com/MinghanLi/UniVS/blob/main/datasets/data_utils/convert_vipseg_to_cocovid.py), [VSS](https://github.com/MinghanLi/UniVS/blob/main/datasets/data_utils/convert_vspw_to_cocovid_val.py), or [VPS](https://github.com/MinghanLi/UniVS/blob/main/datasets/data_utils/convert_vipseg_to_cocovid.py) files 
3. Register the custom dataset in Detectron2 based on [VIS](https://github.com/MinghanLi/UniVS/blob/main/univs/data/datasets/ytvis.py), [VSS](https://github.com/MinghanLi/UniVS/blob/main/univs/data/datasets/vss.py), or [VPS](https://github.com/MinghanLi/UniVS/blob/main/univs/data/datasets/vps.py)

By following these steps, your dataset will be properly prepared for training and aligned with UniVS’s requirements. If further issues arise, feel free to reach out for assistance.

**Comment by ljh-7** [comment]
> To fine-tune UniVS on the custom dataset, you need to convert it into a supported structure. For more details, please refer to the dataset [README.md](https://github.com/MinghanLi/UniVS/tree/main/datasets). Here are the basic instructions:
> 
> 1. Convert your data into the standard [VIS (YTVIS2021)](https://competitions.codalab.org/competitions/28988), [VSS (VSPW)](https://github.com/VSPW-dataset/VSPW-dataset-download), or [VPS (VIPSeg)](https://github.com/VIPSeg-Dataset/VIPSeg-Dataset/tree/main) annotation formats
> 2. Convert the data into the supported structure by using the [VIS](https://github.com/MinghanLi/UniVS/blob/main/datasets/data_utils/convert_vipseg_to_cocovid.py), [VSS](https://github.com/MinghanLi/UniVS/blob/main/datasets/data_utils/convert_vspw_to_cocovid_val.py), or [VPS](https://github.com/MinghanLi/UniVS/blob/main/datasets/data_utils/convert_vipseg_to_cocovid.py) files
> 3. Register the custom dataset in Detectron2 based on [VIS](https://github.com/MinghanLi/UniVS/blob/main/univs/data/datasets/ytvis.py), [VSS](https://github.com/MinghanLi/UniVS/blob/main/univs/data/datasets/vss.py), or [VPS](https://github.com/MinghanLi/UniVS/blob/main/univs/data/datasets/vps.py)
> 
> By following these steps, your dataset will be properly prepared for training and aligned with UniVS’s requirements. If further issues arise, feel free to reach out for assistance.

Thanks a lot！

**Comment by ljh-7** [comment]
> To fine-tune UniVS on the custom dataset, you need to convert it into a supported structure. For more details, please refer to the dataset [README.md](https://github.com/MinghanLi/UniVS/tree/main/datasets). Here are the basic instructions:
> 
> 1. Convert your data into the standard [VIS (YTVIS2021)](https://competitions.codalab.org/competitions/28988), [VSS (VSPW)](https://github.com/VSPW-dataset/VSPW-dataset-download), or [VPS (VIPSeg)](https://github.com/VIPSeg-Dataset/VIPSeg-Dataset/tree/main) annotation formats
> 2. Convert the data into the supported structure by using the [VIS](https://github.com/MinghanLi/UniVS/blob/main/datasets/data_utils/convert_vipseg_to_cocovid.py), [VSS](https://github.com/MinghanLi/UniVS/blob/main/datasets/data_utils/convert_vspw_to_cocovid_val.py), or [VPS](https://github.com/MinghanLi/UniVS/blob/main/datasets/data_utils/convert_vipseg_to_cocovid.py) files
> 3. Register the custom dataset in Detectron2 based on [VIS](https://github.com/MinghanLi/UniVS/blob/main/univs/data/datasets/ytvis.py), [VSS](https://github.com/MinghanLi/UniVS/blob/main/univs/data/datasets/vss.py), or [VPS](https://github.com/MinghanLi/UniVS/blob/main/univs/data/datasets/vps.py)
> 
> By following these steps, your dataset will be properly prepared for training and aligned with UniVS’s requirements. If further issues arise, feel free to reach out for assistance.

So，If my task is video instance segment， what should I do is:
firstly，convert my data into the form of VIS

**Comment by ljh-7** [comment]
> To fine-tune UniVS on the custom dataset, you need to convert it into a supported structure. For more details, please refer to the dataset [README.md](https://github.com/MinghanLi/UniVS/tree/main/datasets). Here are the basic instructions:
> 
> 1. Convert your data into the standard [VIS (YTVIS2021)](https://competitions.codalab.org/competitions/28988), [VSS (VSPW)](https://github.com/VSPW-dataset/VSPW-dataset-download), or [VPS (VIPSeg)](https://github.com/VIPSeg-Dataset/VIPSeg-Dataset/tree/main) annotation formats
> 2. Convert the data into the supported structure by using the [VIS](https://github.com/MinghanLi/UniVS/blob/main/datasets/data_utils/convert_vipseg_to_cocovid.py), [VSS](https://github.com/MinghanLi/UniVS/blob/main/datasets/data_utils/convert_vspw_to_cocovid_val.py), or [VPS](https://github.com/MinghanLi/UniVS/blob/main/datasets/data_utils/convert_vipseg_to_cocovid.py) files
> 3. Register the custom dataset in Detectron2 based on [VIS](https://github.com/MinghanLi/UniVS/blob/main/univs/data/datasets/ytvis.py), [VSS](https://github.com/MinghanLi/UniVS/blob/main/univs/data/datasets/vss.py), or [VPS](https://github.com/MinghanLi/UniVS/blob/main/univs/data/datasets/vps.py)
> 
> By following these steps, your dataset will be properly prepared for training and aligned with UniVS’s requirements. If further issues arise, feel free to reach out for assistance.

So， if my task is video instance segment, what should i do is 
1.firstly ,convert my dataset into the following form of VIS 
![1](https://github.com/user-attachments/assets/5bec24f5-a17b-4c2f-b7ec-30a90b62b8bb)
2.Secondly , using the https://github.com/MinghanLi/UniVS/blob/main/datasets/data_utils/convert_vipseg_to_cocovid.py to convert it into coco structure.
3.Register the custom dataset in Detectron2
4.Modify configs to replace the base model and training set
