### ISSUE TITLE
Releasing the weights of the last training stage

### ISSUE THREAD

**Issue by Amshaker** [MinghanLi/UniVS#2]
Hi,

Thank you for your work! Can you please release the final model weights of the last training stage?

Best Regards,
Abdelrahman.

**Comment by MinghanLi** [comment]
Thanks for your attention. We plan to release the final model weights of training stage 3 in the next two weeks. Now, you can try UniVS with the model weights of stage 2. Experimental results show that the models trained from stage 2 can obtain above 95% performance on most video segmentation benchmarks.
