### ISSUE TITLE
demo and visualization

### ISSUE THREAD

**Issue by zjl603** [MinghanLi/UniVS#4]
Thank you for your great work !

And is there a visualization demo in the repo? How do I get the inference results like the pictures displayed on the project homepage?

By the way, when I follow the installation instructions, I find that there is no "make.sh" in the "mask2former/modeling/pixel_decoder/ops". And when I use the "make.sh" in the original Mask2former repo and finish all the installation instructions, I run the command "sh tools/test/individual_task/test_pvos.sh" and get an error like this:

![2024-03-27_19-48](https://github.com/MinghanLi/UniVS/assets/145190359/90cc75c6-1b72-445a-83b4-982f9fbb0b56)

Thank you for your attention ! !

**Comment by MinghanLi** [comment]
Thank you so much for your valuable feedbacks.  

For visualization demo and inference details, we've just updated the README.md with more guidance. Please follow the detailed steps to visualize or evaluate.

We accidentally ignored all .sh files in .gitignore, and have now uploaded it to the repo. Very sorry about this. BTW, we **do not** change anything about the `make.sh`. So it is okay to use the `make.sh` in the original Mask2former repo. It looks like the error comes from the compiler with C++. We recommend you to look for similar errors and solutions from the Issues of the Mask2former repository.

If you have any questions, please post them here until you can run it.

**Comment by MinghanLi** [comment]
> Thank you for your great work !
> 
> And is there a visualization demo in the repo? How do I get the inference results like the pictures displayed on the project homepage?
> 
> By the way, when I follow the installation instructions, I find that there is no "make.sh" in the "mask2former/modeling/pixel_decoder/ops". And when I use the "make.sh" in the original Mask2former repo and finish all the installation instructions, I run the command "sh tools/test/individual_task/test_pvos.sh" and get an error like this:
> 
> ![2024-03-27_19-48](https://private-user-images.githubusercontent.com/145190359/317251170-90cc75c6-1b72-445a-83b4-982f9fbb0b56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjQzOTYsIm5iZiI6MTcxMjc2NDA5NiwicGF0aCI6Ii8xNDUxOTAzNTkvMzE3MjUxMTcwLTkwY2M3NWM2LTFiNzItNDQ1YS04M2I0LTk4MmY5ZmJiMGI1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxNTQ4MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTA2YTNlN2Q0ZGY4MDA4NTkwMmYxOWNmYTI1ZDcwODMwMTM1MGQ0ZWU1ZmJkYjQxMmQ5MjU5NWMyZjJjMTcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pl9lnB4AfHzOf55HtyN84XksjwA6k_tCuTR9p2jriBI)
> 
> Thank you for your attention ! !

Hi, we have add the code for custom videos with any video format (mp4, avi, mov) or seperated video frames. It just needs two steps: put the custom video in path and then run it. Please see more instraction in README file. Until now, it only support category-guided VS tasks. We will add prompt-guided VS tasks later. Enjoy! :)
