### ISSUE TITLE
torchvision issue

### ISSUE THREAD

**Issue by JJ000n** [MinghanLi/UniVS#6]
In installation part, the torchvision version is 0.11.2. But torchvision.io.read_video function's output_format parameter is not defined in that version. It can use with torchvision version 0.13. 

            vframes, aframes, info = torchvision.io.read_video(
                filename=path, pts_unit="sec", output_format="TCHW"
            )

**Comment by MinghanLi** [comment]
> In installation part, the torchvision version is 0.11.2. But torchvision.io.read_video function's output_format parameter is not defined in that version. It can use with torchvision version 0.13.
> 
> ```
>         vframes, aframes, info = torchvision.io.read_video(
>             filename=path, pts_unit="sec", output_format="TCHW"
>         )
> ```

We've recently updated our code to include tests for custom videos. This requires a newer version of PyTorch to support the original video reading. Thank you for your remained, we have updated the installation file from torch 1.x to torch 2.x. please check [INSTALL.md](https://github.com/MinghanLi/UniVS/blob/main/INSTALL.md).

**Comment by JJ000n** [comment]
Thank you for answering my question.

Thank you once again for sharing excellent research and code.

With the modifications you made, I was able to successfully execute the code with a custom dataset.

I have additional questions.

Which part of the code should I refer to if I want to convert the inference result solely into a panoptic semantic map? In other words, I mean to say without any overlapping with the original photo or without any label tags attached.

Also, is it possible to modify the classification to only focus on the categories I want? If so, which part should I refer to for this modification? I would be really grateful for your guidance on this.

**Comment by MinghanLi** [comment]
You can find all related code in [inference_video_entity.py](https://github.com/MinghanLi/UniVS/blob/main/univs/inference/inference_video_entity.py).

Q1: If you want to output the panoptic semantic map, change the below code: from `self.visualize_results_enable = True if custom_videos_enable else False` to `self.visualize_results_enable = False`  [Line 165](https://github.com/MinghanLi/UniVS/blob/ba391a119db55c036f98385193ae9ee17c4e50bf/univs/inference/inference_video_entity.py#L165).

For your better understanding, please refer to the below code about VPS task.
[output the single panoptic semantic maps](https://github.com/MinghanLi/UniVS/blob/ba391a119db55c036f98385193ae9ee17c4e50bf/univs/inference/inference_video_entity.py#L413) and [visualize_results_vps](https://github.com/MinghanLi/UniVS/blob/ba391a119db55c036f98385193ae9ee17c4e50bf/univs/inference/inference_video_entity.py#L1261)

Q2: For categories, we provide several options, including 'vipseg', 'entityseg' and 'coco'. Please refer to code [here](https://github.com/MinghanLi/UniVS/blob/ba391a119db55c036f98385193ae9ee17c4e50bf/univs/inference/inference_video_entity.py#L174). What you need to do is add a new row into [.sh file](https://github.com/MinghanLi/UniVS/blob/main/tools/test_custom_videos/test_custom_videos.sh):

`MODEL.UniVS.TEST.VIDEO_UNIFIED_INFERENCE_ENTITIES 'entity_vis_coco'`

For custom categories, you may follow the referring segmentation task, where you need to replace the object expressions with object categories from [here](https://github.com/MinghanLi/UniVS/blob/ba391a119db55c036f98385193ae9ee17c4e50bf/tools/test_custom_videos/test_custom_videos_text.sh#L8).

Alternatively, you can build a dataset register in D2 format. For your convinience, there are some examples [coco_panoptic](https://github.com/MinghanLi/UniVS/blob/main/univs/data/datasets/coco_panoptic.py) and [dataset in D2](https://github.com/facebookresearch/detectron2/tree/main/detectron2/data/datasets).

**Comment by JJ000n** [comment]
Based on the answer you provided, I was able to solve many problems. Thank you.  : )

I have an additional question.

 I'm trying to convert my video dataset into segmentation using inference code for custom video. However, when I give a video composed of 16 frames of size 512x512 as input to the A100 (80GB) GPU I'm using, I keep encountering out of memory issues. Can I get advice on this? Initially, the code runs without any issues and successfully performs inference, but shortly after, OOM errors occur. I think there might be a solution to this, but I'm not sure.

**Comment by MinghanLi** [comment]
Some parameters can be changed to keep good balance between performance and memory:
```
INPUT.SAMPLING_FRAME_NUM 5 \              # number of frames per clip
MODEL.BoxVIS.TEST.NUM_FRAMES_WINDOW 5 \   #  >= SAMPLING_FRAME_NUM
MODEL.BoxVIS.TEST.CLIP_STRIDE  3 \        # larger stride between clips, < SAMPLING_FRAME_NUM
MODEL.BoxVIS.TEST.APPLY_CLS_THRES 0.3 \   # use higher score threshold 
```
The corresponding code of those parameters can be found from [here](https://github.com/MinghanLi/UniVS/blob/f1003b31e2d2e5fbdadc25ff27b390165ec46f67/univs/inference/inference_video_entity.py#L221).

By the way, we will release the corresponding pip package for this code tomorrow, making it easier to perform inference on custom images and videos. We are currently doing the final functionality double-check, and it will be ready soon.
