### ISSUE TITLE
Hello author, may I ask why there is no stage1.sh file in the tools file

### ISSUE THREAD

**Issue by Z0721Z** [MinghanLi/UniVS#7]

**Comment by MinghanLi** [comment]
Thanks for your attantion. 

Stage1 is trained on two machines, each equipped with eight V100 or A100 GPUs, and the code supports PyTorch's native multi-node and multi-GPU parallelism. If you want to train Stage1, you simply need to modify the configuration file for Stage2 located in the tools directory. Here are the steps:

Step 1: Configure the parameters for multi-node and multi-GPU parallelism. For detailed instructions, refer to [Detectron2's launch script documentation](https://github.com/facebookresearch/detectron2/blob/0ae803b1449cd2d3f8fa1b7c0f59356db10b3083/detectron2/engine/launch.py#L27).

Step 2: Change [the configuration file](https://github.com/MinghanLi/UniVS/blob/main/tools/run/univs_r50_stage2.sh) from --config-file configs/univs/univs_r50_stage2.yaml to --config-file configs/univs/univs_r50_stage1.yaml.

**Comment by 1404710698** [comment]
Again, I would like to inform 
cfg. MODEL. UniVS.CLIP_CLASS_EMBED_PATH = 'datasets/concept_emb/combined_datasets_cls_emb_rn50x4.pth' where should I download the weight file here, thank you very much!

**Comment by MinghanLi** [comment]
Dear Zhao,

You can find more detailed instructionz from
https://github.com/MinghanLi/UniVS/blob/main/datasets/README.md . Thanks.

Best,
Minghan

zhao ***@***.***> 于2024年5月16日周四 17:07写道：

**Comment by Z0721Z** [comment]
Thanks to the author for the reply and I wish you all the best in your work!
