### ISSUE TITLE
some inference problems

### ISSUE THREAD

**Issue by Sillyyk** [MinghanLi/UniVS#9]
hi！Why did I choose to use category guided vs tasks (self. visualizeResults'only_enable=False), which also allows me to provide a pre trained model for clips.

**Comment by MinghanLi** [comment]
Can you provide more detailes about your questions? Please explain them one-by-one. I would like to help you better understand and address each issue.

**Comment by Sillyyk** [comment]
> Can you provide more detailes about your questions? Please explain them one-by-one. I would like to help you better understand and address each issue.

i follow "https://github.com/MinghanLi/UniVS#category-guided-vs-tasks-vis-vss-vps" , （setup self. visualizeResults'only_enable=False）when it comes to step2 ,sth wrong :FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/regionclip/regionclip/regionclip_pretrained-cc_rn50x4_only_lang_encoder.pth',i download this but i cant find the path. btw step2 "tools" is repeated.

**Comment by MinghanLi** [comment]
Step 1: You can download the 'regionclip_pretrained-cc_rn50x4_only_lang_encoder.pth' file from [here](https://github.com/MinghanLi/UniVS/blob/main/Model_zoo.md#2-prepare-clip-text-encoder--category-embeddings). 
Step 2: Put the .pth file into the directory `'pretrained/regionclip/regionclip/'

```
$ cd UniVS
$ mkdir pretrained
$ mkdir pretrained/regionclip/
$ mkdir pretrained/regionclip/regionclip/
$ mv /your/path/to/the/file pretrained/regionclip/regionclip/
```

Thanks for your reminder, "tools/tools/" shuld be "tools/". I have corrected them now.

**Comment by Sillyyk** [comment]
> Step 1: You can download the 'regionclip_pretrained-cc_rn50x4_only_lang_encoder.pth' file from [here](https://github.com/MinghanLi/UniVS/blob/main/Model_zoo.md#2-prepare-clip-text-encoder--category-embeddings). Step 2: Put the .pth file into the directory `'pretrained/regionclip/regionclip/'
> 
> ```
> $ cd UniVS
> $ mkdir pretrained
> $ mkdir pretrained/regionclip/
> $ mkdir pretrained/regionclip/regionclip/
> $ mv /your/path/to/the/file pretrained/regionclip/regionclip/
> ```
> 
> Thanks for your reminder, "tools/tools/" shuld be "tools/". I have corrected them now.

thanks for your kind reply.The code can run,but according to "https://github.com/MinghanLi/UniVS#category-guided-vs-tasks-vis-vss-vps" , step3 ,i cant find "output/inf/custom_videos/inference",do I need to create this path ? 

After running step 2's sh, it was found that only "results/inference/vps.custom_idos " had new content, which seemed to be the same as the original video.

**Comment by MinghanLi** [comment]
It is my bad. The predicted results should be shown in `datasets/custom_videos/inference`. By the way, you can modify the output path from the config file [here](https://github.com/MinghanLi/UniVS/blob/4e31af00d5a81b35b3ad0b7919167de98a47bb27/tools/test_custom_videos/test_custom_videos.sh#L11). Thank you so much.

If there has any issues, please feel free to contact me. Cheers!

**Comment by Sillyyk** [comment]
> It is my bad. The predicted results should be shown in `datasets/custom_videos/inference`. By the way, you can modify the output path from the config file [here](https://github.com/MinghanLi/UniVS/blob/4e31af00d5a81b35b3ad0b7919167de98a47bb27/tools/test_custom_videos/test_custom_videos.sh#L11). Thank you so much.
> 
> If there has any issues, please feel free to contact me. Cheers!

thank you,i want to ask why did some masks disappear during testing, with tails of 4 and 9.

**Comment by MinghanLi** [comment]
There are some parameters in UniVS to control the mask quality and remove some masks, including bounding box IoU, classification confidence, temporal consistency, and so on. You can refer to the [code](https://github.com/MinghanLi/UniVS/blob/d689ef88890d8f85f087eb3bfcea7d61dc0b7d1a/univs/inference/inference_video_entity.py#L77) and try to set them according to your requirements.

**Comment by Sillyyk** [comment]
Thank you for your answer. At the same time, I would like to add that some parameters need to be modified in the specific configuration to be effective. For example, I solved the problem by adding SAMPLING-FRAME.NUM: 6 in "univs_swinb_text_c1+univs_entity. yaml". Thank you again for your answer. Your work is as beautiful as yours.

**Comment by MinghanLi** [comment]
Thanks. I would like to close this issue now.
